global:
  scrape_interval: 15s
  evaluation_interval: 15s
  
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'strapi-admin'
    static_configs:
      - targets: ['strapi-admin:1337']  # 👈 this works because of the shared Docker network

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']