apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090  # Use the Prometheus container name from your Docker Compose
    isDefault: true
